<?php
/**
 * Created by PhpStorm.
 * User: alexander.andreev
 * Date: 05.07.2017
 * Time: 18:08
 */

namespace app\components;

use yii\base\Widget;

class CategoryWidget extends Widget
{
    public $id;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if($this->id === null)
        {
            $this->id = 0;
        }
    }

    public function run()
    {
        return $this->render('category', ['id'=>$this->id]);
    }
}